"""phase4_operational_engine

Revision ID: 0e881b3debad
Revises: f00940ddeebc
Create Date: 2026-09-10 09:17:48.174773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e881b3debad'
down_revision: Union[str, Sequence[str], None] = 'f00940ddeebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('booking_type', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) between 2 and 160', name=op.f('ck_rate_cards_ck_rate_card_name_len')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_rate_cards_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_rate_cards_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_cards'))
    )
    op.create_index(op.f('ix_rate_cards_customer_id'), 'rate_cards', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rate_cards_organisation_id'), 'rate_cards', ['organisation_id'], unique=False)
    op.create_table('rate_card_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_card_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_km_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extra_hour_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('night_allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], name=op.f('fk_rate_card_versions_rate_card_id_rate_cards'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_card_versions')),
    sa.UniqueConstraint('rate_card_id', 'version_number', name='uq_rate_card_version')
    )
    op.create_index(op.f('ix_rate_card_versions_rate_card_id'), 'rate_card_versions', ['rate_card_id'], unique=False)
    op.create_table('booking_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_number', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.Enum('ETS', 'SPOT', 'FIXED', 'RENTAL', 'AIRPORT', 'LOCAL', 'OUTSTATION', 'CORPORATE', 'CONTRACT', 'RECURRING', name='booking_type'), nullable=False),
    sa.Column('service_type', sa.Enum('PASSENGER', 'CARGO', name='booking_service_type'), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('drop_address', sa.Text(), nullable=False),
    sa.Column('drop_lat', sa.Float(), nullable=True),
    sa.Column('drop_lng', sa.Float(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_completion_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passenger_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cargo_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vehicle_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('rate_card_version_id', sa.UUID(), nullable=True),
    sa.Column('estimated_pricing', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REQUESTED', 'CONFIRMED', 'CANCELLED', name='booking_request_status'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_booking_requests_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_booking_requests_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], name=op.f('fk_booking_requests_rate_card_version_id_rate_card_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_requests')),
    sa.UniqueConstraint('organisation_id', 'request_number', name='uq_booking_req_org_num')
    )
    op.create_index(op.f('ix_booking_requests_customer_id'), 'booking_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_booking_requests_organisation_id'), 'booking_requests', ['organisation_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=64), nullable=False),
    sa.Column('booking_request_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('booking_type', sa.Enum('ETS', 'SPOT', 'FIXED', 'RENTAL', 'AIRPORT', 'LOCAL', 'OUTSTATION', 'CORPORATE', 'CONTRACT', 'RECURRING', name='booking_type'), nullable=False),
    sa.Column('service_type', sa.Enum('PASSENGER', 'CARGO', name='booking_service_type'), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('drop_address', sa.Text(), nullable=False),
    sa.Column('drop_lat', sa.Float(), nullable=True),
    sa.Column('drop_lng', sa.Float(), nullable=True),
    sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_completion_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passenger_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cargo_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vehicle_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('driver_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_card_version_id', sa.UUID(), nullable=True),
    sa.Column('commercial_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operational_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='booking_operational_status'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], name=op.f('fk_bookings_booking_request_id_booking_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_bookings_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_bookings_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], name=op.f('fk_bookings_rate_card_version_id_rate_card_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('organisation_id', 'booking_number', name='uq_booking_org_num')
    )
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_organisation_id'), 'bookings', ['organisation_id'], unique=False)
    op.create_table('duties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duty_number', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ALLOCATED', 'DISPATCHED', 'ARRIVED_PICKUP', 'IN_TRANSIT', 'ARRIVED_DROP', 'DUTY_COMPLETED', 'CANCELLED', name='duty_lifecycle_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('scheduled_end_time >= scheduled_start_time', name=op.f('ck_duties_ck_duty_time_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_duties_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_duties_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_duties_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_duties_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duties')),
    sa.UniqueConstraint('organisation_id', 'duty_number', name='uq_duty_org_num')
    )
    op.create_index(op.f('ix_duties_booking_id'), 'duties', ['booking_id'], unique=False)
    op.create_index(op.f('ix_duties_driver_id'), 'duties', ['driver_id'], unique=False)
    op.create_index(op.f('ix_duties_organisation_id'), 'duties', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_duties_status'), 'duties', ['status'], unique=False)
    op.create_index(op.f('ix_duties_vehicle_id'), 'duties', ['vehicle_id'], unique=False)
    op.create_table('duty_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duty_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'REJECTED', 'SUPERSEDED', name='duty_assignment_status'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_duty_assignments_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], name=op.f('fk_duty_assignments_duty_id_duties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_duty_assignments_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duty_assignments'))
    )
    op.create_index(op.f('ix_duty_assignments_driver_id'), 'duty_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_duty_assignments_duty_id'), 'duty_assignments', ['duty_id'], unique=False)
    op.create_index(op.f('ix_duty_assignments_vehicle_id'), 'duty_assignments', ['vehicle_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_number', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('duty_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_odometer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('end_odometer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_distance_km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('end_location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('toll_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('parking_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('waiting_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='trip_lifecycle_status'), nullable=False),
    sa.Column('pod_attachment_url', sa.String(length=512), nullable=True),
    sa.Column('pod_notes', sa.Text(), nullable=True),
    sa.Column('pod_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operational_receipts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_odometer IS NULL OR end_odometer >= start_odometer', name=op.f('ck_trips_ck_trip_odometer_valid')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_trips_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], name=op.f('fk_trips_duty_id_duties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_trips_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_trips_vehicle_id_vehicles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('organisation_id', 'trip_number', name='uq_trip_org_num')
    )
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_duty_id'), 'trips', ['duty_id'], unique=True)
    op.create_index(op.f('ix_trips_organisation_id'), 'trips', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_table('trip_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_events_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_events'))
    )
    op.create_index(op.f('ix_trip_events_trip_id'), 'trip_events', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_events_trip_id'), table_name='trip_events')
    op.drop_table('trip_events')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_organisation_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_duty_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_duty_assignments_vehicle_id'), table_name='duty_assignments')
    op.drop_index(op.f('ix_duty_assignments_duty_id'), table_name='duty_assignments')
    op.drop_index(op.f('ix_duty_assignments_driver_id'), table_name='duty_assignments')
    op.drop_table('duty_assignments')
    op.drop_index(op.f('ix_duties_vehicle_id'), table_name='duties')
    op.drop_index(op.f('ix_duties_status'), table_name='duties')
    op.drop_index(op.f('ix_duties_organisation_id'), table_name='duties')
    op.drop_index(op.f('ix_duties_driver_id'), table_name='duties')
    op.drop_index(op.f('ix_duties_booking_id'), table_name='duties')
    op.drop_table('duties')
    op.drop_index(op.f('ix_bookings_organisation_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_booking_requests_organisation_id'), table_name='booking_requests')
    op.drop_index(op.f('ix_booking_requests_customer_id'), table_name='booking_requests')
    op.drop_table('booking_requests')
    op.drop_index(op.f('ix_rate_card_versions_rate_card_id'), table_name='rate_card_versions')
    op.drop_table('rate_card_versions')
    op.drop_index(op.f('ix_rate_cards_organisation_id'), table_name='rate_cards')
    op.drop_index(op.f('ix_rate_cards_customer_id'), table_name='rate_cards')
    op.drop_table('rate_cards')

    # Drop custom enums
    op.execute("DROP TYPE IF EXISTS trip_lifecycle_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS duty_assignment_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS duty_lifecycle_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS booking_operational_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS booking_request_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS booking_service_type CASCADE;")
    op.execute("DROP TYPE IF EXISTS booking_type CASCADE;")
    # ### end Alembic commands ###
