"""prompt_06_commander

Revision ID: 10b12c3055fd
Revises: 7ce95b6be418
Create Date: 2026-09-21 11:39:27.838898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b12c3055fd'
down_revision: Union[str, Sequence[str], None] = '7ce95b6be418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_members', sa.Column('is_commander', sa.Boolean(), nullable=False, server_default='false'))
    
    # Initialize the creator as the commander for existing orgs (safeguard)
    op.execute("UPDATE organisation_members SET is_commander = true WHERE is_creator = true")
    
    op.create_index('uq_org_member_commander', 'organisation_members', ['organisation_id'], unique=True, postgresql_where=sa.text('is_commander = true'))
    
    # Fix schema_version null constraints from previous phase
    op.alter_column('tenant_database_registry', 'schema_version', server_default='0')
    op.alter_column('organisation_database_assignments', 'schema_version', server_default='0')
    op.alter_column('tenant_mongodb_registry', 'schema_version', server_default='0')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_database_registry', 'schema_version', server_default=None)
    op.alter_column('organisation_database_assignments', 'schema_version', server_default=None)
    op.alter_column('tenant_mongodb_registry', 'schema_version', server_default=None)
    
    op.drop_index('uq_org_member_commander', table_name='organisation_members', postgresql_where=sa.text('is_commander = true'))
    op.drop_column('organisation_members', 'is_commander')

    # ### end Alembic commands ###
