"""Add tenant migration jobs

Revision ID: 19bd95815ecb
Revises: 18bebbcc318a
Create Date: 2026-09-12 11:50:48.506921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19bd95815ecb'
down_revision: Union[str, Sequence[str], None] = '18bebbcc318a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_migration_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('source_provider', postgresql.ENUM('D1', 'POSTGRESQL', 'MONGODB', 'OTHER', name='providertype', create_type=False), nullable=False),
    sa.Column('destination_provider', postgresql.ENUM('D1', 'POSTGRESQL', 'MONGODB', 'OTHER', name='providertype', create_type=False), nullable=False),
    sa.Column('destination_database_identifier', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'VALIDATING_SOURCE', 'PROVISIONING_DESTINATION', 'SCHEMA_PREPARATION', 'DATA_EXPORT', 'DATA_TRANSFORMATION', 'DATA_IMPORT', 'RECONCILIATION', 'RUNTIME_VALIDATION', 'PILOT_READY', 'MIGRATION_FAILED', 'MIGRATION_CANCELLED', name='migrationstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reconciliation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runtime_validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_tenant_migration_jobs_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_migration_jobs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_migration_jobs')
    # ### end Alembic commands ###
