"""Add Phase 5.1 tables

Revision ID: 22ad882c52f6
Revises: ad3946b45aba
Create Date: 2026-09-12 08:18:37.520528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ad882c52f6'
down_revision: Union[str, Sequence[str], None] = 'ad3946b45aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='financial_period_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['profiles.id'], name=op.f('fk_financial_periods_closed_by_user_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_financial_periods_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_periods')),
    sa.UniqueConstraint('organisation_id', 'period_name', name='uq_financial_period_org_name')
    )
    op.create_index(op.f('ix_financial_periods_organisation_id'), 'financial_periods', ['organisation_id'], unique=False)
    op.create_table('financial_adjustment_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.Enum('CREDIT', 'DEBIT', name='adjustment_note_type'), nullable=False),
    sa.Column('note_number', sa.String(length=64), nullable=False),
    sa.Column('note_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'CANCELLED', name='adjustment_note_status'), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_financial_adjustment_notes_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_financial_adjustment_notes_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_financial_adjustment_notes_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_adjustment_notes')),
    sa.UniqueConstraint('organisation_id', 'note_type', 'note_number', name='uq_adjustment_note_num')
    )
    op.create_index(op.f('ix_financial_adjustment_notes_customer_id'), 'financial_adjustment_notes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_financial_adjustment_notes_invoice_id'), 'financial_adjustment_notes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_financial_adjustment_notes_note_number'), 'financial_adjustment_notes', ['note_number'], unique=False)
    op.create_index(op.f('ix_financial_adjustment_notes_organisation_id'), 'financial_adjustment_notes', ['organisation_id'], unique=False)
    op.create_table('vendor_settlement_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('statement_number', sa.String(length=64), nullable=False),
    sa.Column('statement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gross_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_advances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_vendor_settlement_statements_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_vendor_settlement_statements_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_settlement_statements_vendor_id_vendors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_settlement_statements')),
    sa.UniqueConstraint('organisation_id', 'statement_number', name='uq_vendor_settlement_num')
    )
    op.create_index(op.f('ix_vendor_settlement_statements_driver_id'), 'vendor_settlement_statements', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_statements_organisation_id'), 'vendor_settlement_statements', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_statements_statement_number'), 'vendor_settlement_statements', ['statement_number'], unique=False)
    op.create_index(op.f('ix_vendor_settlement_statements_vendor_id'), 'vendor_settlement_statements', ['vendor_id'], unique=False)
    op.create_table('financial_adjustment_note_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['financial_adjustment_notes.id'], name=op.f('fk_financial_adjustment_note_lines_note_id_financial_adjustment_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_adjustment_note_lines'))
    )
    op.create_index(op.f('ix_financial_adjustment_note_lines_note_id'), 'financial_adjustment_note_lines', ['note_id'], unique=False)
    op.create_table('financial_adjustment_note_tax_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('tax_name', sa.String(length=64), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['financial_adjustment_notes.id'], name=op.f('fk_financial_adjustment_note_tax_lines_note_id_financial_adjustment_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_adjustment_note_tax_lines'))
    )
    op.create_index(op.f('ix_financial_adjustment_note_tax_lines_note_id'), 'financial_adjustment_note_tax_lines', ['note_id'], unique=False)
    op.add_column('invoices', sa.Column('pdf_url', sa.String(length=512), nullable=True))
    op.add_column('invoices', sa.Column('cancellation_reason', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'cancellation_reason')
    op.drop_column('invoices', 'pdf_url')
    op.drop_index(op.f('ix_financial_adjustment_note_tax_lines_note_id'), table_name='financial_adjustment_note_tax_lines')
    op.drop_table('financial_adjustment_note_tax_lines')
    op.drop_index(op.f('ix_financial_adjustment_note_lines_note_id'), table_name='financial_adjustment_note_lines')
    op.drop_table('financial_adjustment_note_lines')
    op.drop_index(op.f('ix_vendor_settlement_statements_vendor_id'), table_name='vendor_settlement_statements')
    op.drop_index(op.f('ix_vendor_settlement_statements_statement_number'), table_name='vendor_settlement_statements')
    op.drop_index(op.f('ix_vendor_settlement_statements_organisation_id'), table_name='vendor_settlement_statements')
    op.drop_index(op.f('ix_vendor_settlement_statements_driver_id'), table_name='vendor_settlement_statements')
    op.drop_table('vendor_settlement_statements')
    op.drop_index(op.f('ix_financial_adjustment_notes_organisation_id'), table_name='financial_adjustment_notes')
    op.drop_index(op.f('ix_financial_adjustment_notes_note_number'), table_name='financial_adjustment_notes')
    op.drop_index(op.f('ix_financial_adjustment_notes_invoice_id'), table_name='financial_adjustment_notes')
    op.drop_index(op.f('ix_financial_adjustment_notes_customer_id'), table_name='financial_adjustment_notes')
    op.drop_table('financial_adjustment_notes')
    op.drop_index(op.f('ix_financial_periods_organisation_id'), table_name='financial_periods')
    op.drop_table('financial_periods')
    # ### end Alembic commands ###
