"""update_customization_models_and_pages

Revision ID: 4add22c81123
Revises: a3075070cbf6
Create Date: 2026-09-21 10:51:00.492059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4add22c81123'
down_revision: Union[str, Sequence[str], None] = 'a3075070cbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('page_code', sa.String(), nullable=False),
    sa.Column('action_code', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_actions_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_actions'))
    )
    op.create_index(op.f('ix_application_actions_application_id'), 'application_actions', ['application_id'], unique=False)
    op.create_table('application_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(), nullable=False),
    sa.Column('page_code', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_pages_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_pages'))
    )
    op.create_index(op.f('ix_application_pages_application_id'), 'application_pages', ['application_id'], unique=False)
    op.drop_index(op.f('ix_application_approvals_customer_id'), table_name='application_approvals')
    op.drop_column('application_approvals', 'customer_id')
    op.drop_index(op.f('ix_application_configurations_customer_id'), table_name='application_configurations')
    op.drop_column('application_configurations', 'customer_id')
    op.drop_index(op.f('ix_application_forms_customer_id'), table_name='application_forms')
    op.drop_column('application_forms', 'customer_id')
    op.drop_index(op.f('ix_application_modules_customer_id'), table_name='application_modules')
    op.drop_column('application_modules', 'customer_id')
    op.drop_index(op.f('ix_application_reports_customer_id'), table_name='application_reports')
    op.drop_column('application_reports', 'customer_id')
    op.drop_index(op.f('ix_application_rules_customer_id'), table_name='application_rules')
    op.drop_column('application_rules', 'customer_id')
    op.drop_index(op.f('ix_application_workflows_customer_id'), table_name='application_workflows')
    op.drop_column('application_workflows', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_workflows', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_workflows_customer_id'), 'application_workflows', ['customer_id'], unique=False)
    op.add_column('application_rules', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_rules_customer_id'), 'application_rules', ['customer_id'], unique=False)
    op.add_column('application_reports', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_reports_customer_id'), 'application_reports', ['customer_id'], unique=False)
    op.add_column('application_modules', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_modules_customer_id'), 'application_modules', ['customer_id'], unique=False)
    op.add_column('application_forms', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_forms_customer_id'), 'application_forms', ['customer_id'], unique=False)
    op.add_column('application_configurations', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_configurations_customer_id'), 'application_configurations', ['customer_id'], unique=False)
    op.add_column('application_approvals', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_application_approvals_customer_id'), 'application_approvals', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_application_pages_application_id'), table_name='application_pages')
    op.drop_table('application_pages')
    op.drop_index(op.f('ix_application_actions_application_id'), table_name='application_actions')
    op.drop_table('application_actions')
    # ### end Alembic commands ###
