"""add_crm_domain_models

Revision ID: 588a89f2fc81
Revises: 4add22c81123
Create Date: 2026-09-21 10:53:51.062893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588a89f2fc81'
down_revision: Union[str, Sequence[str], None] = '4add22c81123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('billing_address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ONBOARDING', 'SUSPENDED', name='client_status', create_type=False), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_clients_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_organisation_id'), 'clients', ['organisation_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('vendor_type', sa.Enum('TRANSPORTER', 'BROKER', 'FUEL_STATION', 'MAINTENANCE', 'OTHER', name='vendor_type', create_type=False), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ONBOARDING', 'SUSPENDED', name='vendor_status', create_type=False), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_vendors_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_organisation_id'), 'vendors', ['organisation_id'], unique=False)
    op.create_table('client_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('operating_unit_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ONBOARDING', 'SUSPENDED', name='client_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_locations_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operating_unit_id'], ['operating_units.id'], name=op.f('fk_client_locations_operating_unit_id_operating_units'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_locations'))
    )
    op.create_index(op.f('ix_client_locations_client_id'), 'client_locations', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_locations_operating_unit_id'), 'client_locations', ['operating_unit_id'], unique=False)
    op.create_table('client_location_ou_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_location_id', sa.UUID(), nullable=False),
    sa.Column('previous_operating_unit_id', sa.UUID(), nullable=True),
    sa.Column('new_operating_unit_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_location_id'], ['client_locations.id'], name=op.f('fk_client_location_ou_history_client_location_id_client_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_operating_unit_id'], ['operating_units.id'], name=op.f('fk_client_location_ou_history_new_operating_unit_id_operating_units'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_operating_unit_id'], ['operating_units.id'], name=op.f('fk_client_location_ou_history_previous_operating_unit_id_operating_units'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_location_ou_history'))
    )
    op.create_index(op.f('ix_client_location_ou_history_client_location_id'), 'client_location_ou_history', ['client_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_location_ou_history_client_location_id'), table_name='client_location_ou_history')
    op.drop_table('client_location_ou_history')
    op.drop_index(op.f('ix_client_locations_operating_unit_id'), table_name='client_locations')
    op.drop_index(op.f('ix_client_locations_client_id'), table_name='client_locations')
    op.drop_table('client_locations')
    op.drop_index(op.f('ix_vendors_organisation_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_clients_organisation_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
