"""add customization platform tables

Revision ID: 5cf10f6c9db7
Revises: 19bd95815ecb
Create Date: 2026-09-15 07:27:04.218466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cf10f6c9db7'
down_revision: Union[str, Sequence[str], None] = '19bd95815ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('application_type', sa.Enum('STANDARD', 'CONFIGURED', 'EXTENDED', 'CUSTOM', name='applicationtype'), nullable=False),
    sa.Column('application_name', sa.String(), nullable=False),
    sa.Column('application_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_applications_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_applications'))
    )
    op.create_index(op.f('ix_organisation_applications_organisation_id'), 'organisation_applications', ['organisation_id'], unique=False)
    op.create_table('application_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('approval_chain_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_approvals_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_approvals'))
    )
    op.create_index(op.f('ix_application_approvals_application_id'), 'application_approvals', ['application_id'], unique=False)
    op.create_table('application_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('config_type', sa.Enum('NAVIGATION', 'THEME', 'TERMINOLOGY', 'NUMBERING', 'NOTIFICATIONS', 'DOCUMENT_TEMPLATES', 'EXTENSIONS', 'CUSTOM_REFS', name='configtype'), nullable=False),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_configurations_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_configurations'))
    )
    op.create_index(op.f('ix_application_configurations_application_id'), 'application_configurations', ['application_id'], unique=False)
    op.create_table('application_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=False),
    sa.Column('fields_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_forms_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_forms'))
    )
    op.create_index(op.f('ix_application_forms_application_id'), 'application_forms', ['application_id'], unique=False)
    op.create_table('application_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_modules_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_modules'))
    )
    op.create_index(op.f('ix_application_modules_application_id'), 'application_modules', ['application_id'], unique=False)
    op.create_table('application_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('report_name', sa.String(), nullable=False),
    sa.Column('entity_source', sa.String(), nullable=False),
    sa.Column('report_definition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_reports_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_reports'))
    )
    op.create_index(op.f('ix_application_reports_application_id'), 'application_reports', ['application_id'], unique=False)
    op.create_table('application_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_rules_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_rules'))
    )
    op.create_index(op.f('ix_application_rules_application_id'), 'application_rules', ['application_id'], unique=False)
    op.create_table('application_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('definition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['organisation_applications.id'], name=op.f('fk_application_workflows_application_id_organisation_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_workflows'))
    )
    op.create_index(op.f('ix_application_workflows_application_id'), 'application_workflows', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_workflows_application_id'), table_name='application_workflows')
    op.drop_table('application_workflows')
    op.drop_index(op.f('ix_application_rules_application_id'), table_name='application_rules')
    op.drop_table('application_rules')
    op.drop_index(op.f('ix_application_reports_application_id'), table_name='application_reports')
    op.drop_table('application_reports')
    op.drop_index(op.f('ix_application_modules_application_id'), table_name='application_modules')
    op.drop_table('application_modules')
    op.drop_index(op.f('ix_application_forms_application_id'), table_name='application_forms')
    op.drop_table('application_forms')
    op.drop_index(op.f('ix_application_configurations_application_id'), table_name='application_configurations')
    op.drop_table('application_configurations')
    op.drop_index(op.f('ix_application_approvals_application_id'), table_name='application_approvals')
    op.drop_table('application_approvals')
    op.drop_index(op.f('ix_organisation_applications_organisation_id'), table_name='organisation_applications')
    op.drop_table('organisation_applications')
    # ### end Alembic commands ###
