"""prompt_05_auth_membership

Revision ID: 7ce95b6be418
Revises: 7e5a1ae448ae
Create Date: 2026-09-21 11:16:27.770620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce95b6be418'
down_revision: Union[str, Sequence[str], None] = '7e5a1ae448ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_invitations_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_invitations'))
    )
    op.create_index(op.f('ix_organisation_invitations_email'), 'organisation_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organisation_invitations_organisation_id'), 'organisation_invitations', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_invitations_token'), 'organisation_invitations', ['token'], unique=True)
    op.add_column('organisation_members', sa.Column('is_creator', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('fk_organisation_members_role_id_roles'), 'organisation_members', type_='foreignkey')
    op.drop_column('organisation_members', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_members', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_organisation_members_role_id_roles'), 'organisation_members', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('organisation_members', 'is_creator')
    op.drop_index(op.f('ix_organisation_invitations_token'), table_name='organisation_invitations')
    op.drop_index(op.f('ix_organisation_invitations_organisation_id'), table_name='organisation_invitations')
    op.drop_index(op.f('ix_organisation_invitations_email'), table_name='organisation_invitations')
    op.drop_table('organisation_invitations')
    # ### end Alembic commands ###
