"""prompt_04_org_domain_model

Revision ID: 7e5a1ae448ae
Revises: d3e09b9e3c13
Create Date: 2026-09-21 11:06:20.989844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5a1ae448ae'
down_revision: Union[str, Sequence[str], None] = 'd3e09b9e3c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ou_id_organisation_id', 'operating_units', ['id', 'organisation_id'])
    op.create_table('client_operating_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('operating_unit_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id', 'organisation_id'], ['clients.id', 'clients.organisation_id'], name='fk_client_ou_client_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operating_unit_id', 'organisation_id'], ['operating_units.id', 'operating_units.organisation_id'], name='fk_client_ou_ou_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_client_operating_units_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_operating_units')),
    sa.UniqueConstraint('client_id', 'operating_unit_id', name='uq_client_ou')
    )
    op.create_index(op.f('ix_client_operating_units_client_id'), 'client_operating_units', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_operating_units_operating_unit_id'), 'client_operating_units', ['operating_unit_id'], unique=False)
    op.create_index(op.f('ix_client_operating_units_organisation_id'), 'client_operating_units', ['organisation_id'], unique=False)
    op.add_column('client_location_ou_history', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_client_location_ou_history_organisation_id'), 'client_location_ou_history', ['organisation_id'], unique=False)
    op.drop_constraint(op.f('fk_client_location_ou_history_previous_operating_unit_i_f34e'), 'client_location_ou_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_client_location_ou_history_client_location_id_client_8b24'), 'client_location_ou_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_client_location_ou_history_new_operating_unit_id_ope_417a'), 'client_location_ou_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_location_ou_history_organisation_id_organisations'), 'client_location_ou_history', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_history_client_location_org', 'client_location_ou_history', 'client_locations', ['client_location_id', 'organisation_id'], ['id', 'organisation_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_history_prev_ou_org', 'client_location_ou_history', 'operating_units', ['previous_operating_unit_id', 'organisation_id'], ['id', 'organisation_id'], ondelete='SET NULL')
    op.create_foreign_key('fk_history_new_ou_org', 'client_location_ou_history', 'operating_units', ['new_operating_unit_id', 'organisation_id'], ['id', 'organisation_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_client_locations_operating_unit_id_operating_units'), 'client_locations', type_='foreignkey')
    op.create_foreign_key('fk_client_location_ou_org', 'client_locations', 'operating_units', ['operating_unit_id', 'organisation_id'], ['id', 'organisation_id'], ondelete='SET NULL')
    op.add_column('operating_unit_locations', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_operating_unit_locations_organisation_id'), 'operating_unit_locations', ['organisation_id'], unique=False)
    op.drop_constraint(op.f('fk_operating_unit_locations_operating_unit_id_operating_units'), 'operating_unit_locations', type_='foreignkey')
    op.create_foreign_key('fk_ou_location_ou_org', 'operating_unit_locations', 'operating_units', ['operating_unit_id', 'organisation_id'], ['id', 'organisation_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_operating_unit_locations_organisation_id_organisations'), 'operating_unit_locations', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_operating_unit_locations_organisation_id_organisations'), 'operating_unit_locations', type_='foreignkey')
    op.drop_constraint('fk_ou_location_ou_org', 'operating_unit_locations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_operating_unit_locations_operating_unit_id_operating_units'), 'operating_unit_locations', 'operating_units', ['operating_unit_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_operating_unit_locations_organisation_id'), table_name='operating_unit_locations')
    op.drop_column('operating_unit_locations', 'organisation_id')
    op.drop_constraint('fk_client_location_ou_org', 'client_locations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_locations_operating_unit_id_operating_units'), 'client_locations', 'operating_units', ['operating_unit_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_history_new_ou_org', 'client_location_ou_history', type_='foreignkey')
    op.drop_constraint('fk_history_prev_ou_org', 'client_location_ou_history', type_='foreignkey')
    op.drop_constraint('fk_history_client_location_org', 'client_location_ou_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_client_location_ou_history_organisation_id_organisations'), 'client_location_ou_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_location_ou_history_new_operating_unit_id_ope_417a'), 'client_location_ou_history', 'operating_units', ['new_operating_unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_client_location_ou_history_client_location_id_client_8b24'), 'client_location_ou_history', 'client_locations', ['client_location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_client_location_ou_history_previous_operating_unit_i_f34e'), 'client_location_ou_history', 'operating_units', ['previous_operating_unit_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_client_location_ou_history_organisation_id'), table_name='client_location_ou_history')
    op.drop_column('client_location_ou_history', 'organisation_id')
    op.drop_index(op.f('ix_client_operating_units_organisation_id'), table_name='client_operating_units')
    op.drop_index(op.f('ix_client_operating_units_operating_unit_id'), table_name='client_operating_units')
    op.drop_index(op.f('ix_client_operating_units_client_id'), table_name='client_operating_units')
    op.drop_table('client_operating_units')
    op.drop_constraint('uq_ou_id_organisation_id', 'operating_units', type_='unique')
# ### end Alembic commands ###
