"""add_operating_units_and_locations

Revision ID: a3075070cbf6
Revises: d12345678901
Create Date: 2026-09-21 10:42:22.821454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3075070cbf6'
down_revision: Union[str, Sequence[str], None] = 'd12345678901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='operating_unit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_operating_units_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_units')),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_org_ou_code')
    )
    op.create_index(op.f('ix_operating_units_organisation_id'), 'operating_units', ['organisation_id'], unique=False)
    op.create_table('operating_unit_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operating_unit_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='operating_unit_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operating_unit_id'], ['operating_units.id'], name=op.f('fk_operating_unit_locations_operating_unit_id_operating_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_unit_locations')),
    sa.UniqueConstraint('operating_unit_id', 'code', name='uq_ou_location_code')
    )
    op.create_index(op.f('ix_operating_unit_locations_operating_unit_id'), 'operating_unit_locations', ['operating_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operating_unit_locations_operating_unit_id'), table_name='operating_unit_locations')
    op.drop_table('operating_unit_locations')
    op.drop_index(op.f('ix_operating_units_organisation_id'), table_name='operating_units')
    op.drop_table('operating_units')
    # ### end Alembic commands ###
