"""prompt_07_roles_permissions

Revision ID: a503d687602f
Revises: 10b12c3055fd
Create Date: 2026-09-21 11:56:53.217132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a503d687602f'
down_revision: Union[str, Sequence[str], None] = '10b12c3055fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_role_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_role_templates'))
    )
    op.create_index(op.f('ix_platform_role_templates_code'), 'platform_role_templates', ['code'], unique=True)
    op.create_table('organisation_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('CUSTOM', 'ORG_TEMPLATE', 'FROM_PLATFORM', name='role_source'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='role_status'), nullable=False),
    sa.Column('platform_template_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_roles_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_template_id'], ['platform_role_templates.id'], name=op.f('fk_organisation_roles_platform_template_id_platform_role_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_roles')),
    sa.UniqueConstraint('organisation_id', 'name', name='uq_org_role_name')
    )
    op.create_index('ix_org_roles_org_status', 'organisation_roles', ['organisation_id', 'status'], unique=False)
    op.create_index(op.f('ix_organisation_roles_organisation_id'), 'organisation_roles', ['organisation_id'], unique=False)
    op.create_table('platform_role_template_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=100), nullable=False),
    sa.Column('page_code', sa.String(length=100), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['platform_role_templates.id'], name=op.f('fk_platform_role_template_permissions_template_id_platform_role_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_role_template_permissions')),
    sa.UniqueConstraint('template_id', 'module_code', 'page_code', 'action_code', name='uq_platform_tpl_permission')
    )
    op.create_index(op.f('ix_platform_role_template_permissions_template_id'), 'platform_role_template_permissions', ['template_id'], unique=False)
    op.create_table('organisation_role_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_note', sa.String(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['organisation_roles.id'], name=op.f('fk_organisation_role_versions_role_id_organisation_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_role_versions')),
    sa.UniqueConstraint('role_id', 'version_number', name='uq_role_version')
    )
    op.create_index(op.f('ix_organisation_role_versions_role_id'), 'organisation_role_versions', ['role_id'], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('override_type', sa.Enum('GRANT', 'RESTRICT', name='override_type'), nullable=False),
    sa.Column('module_code', sa.String(length=100), nullable=False),
    sa.Column('page_code', sa.String(length=100), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['organisation_members.id'], name=op.f('fk_user_permission_overrides_member_id_organisation_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_user_permission_overrides_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permission_overrides')),
    sa.UniqueConstraint('organisation_id', 'member_id', 'override_type', 'module_code', 'page_code', 'action_code', name='uq_user_perm_override')
    )
    op.create_index('ix_user_override_member', 'user_permission_overrides', ['member_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_member_id'), 'user_permission_overrides', ['member_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_organisation_id'), 'user_permission_overrides', ['organisation_id'], unique=False)
    op.create_table('organisation_role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=100), nullable=False),
    sa.Column('page_code', sa.String(length=100), nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['organisation_role_versions.id'], name=op.f('fk_organisation_role_permissions_version_id_organisation_role_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_role_permissions')),
    sa.UniqueConstraint('version_id', 'module_code', 'page_code', 'action_code', name='uq_role_version_permission')
    )
    op.create_index(op.f('ix_organisation_role_permissions_version_id'), 'organisation_role_permissions', ['version_id'], unique=False)
    op.create_index('ix_role_perm_version', 'organisation_role_permissions', ['version_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_version_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['organisation_members.id'], name=op.f('fk_role_assignments_member_id_organisation_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_role_assignments_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['organisation_roles.id'], name=op.f('fk_role_assignments_role_id_organisation_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_version_id'], ['organisation_role_versions.id'], name=op.f('fk_role_assignments_role_version_id_organisation_role_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('organisation_id', 'member_id', name='uq_active_role_assignment')
    )
    op.create_index('ix_role_assignment_member', 'role_assignments', ['member_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_member_id'), 'role_assignments', ['member_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_organisation_id'), 'role_assignments', ['organisation_id'], unique=False)
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.drop_index(op.f('ix_role_assignments_organisation_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_member_id'), table_name='role_assignments')
    op.drop_index('ix_role_assignment_member', table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index('ix_role_perm_version', table_name='organisation_role_permissions')
    op.drop_index(op.f('ix_organisation_role_permissions_version_id'), table_name='organisation_role_permissions')
    op.drop_table('organisation_role_permissions')
    op.drop_index(op.f('ix_user_permission_overrides_organisation_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_member_id'), table_name='user_permission_overrides')
    op.drop_index('ix_user_override_member', table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_index(op.f('ix_organisation_role_versions_role_id'), table_name='organisation_role_versions')
    op.drop_table('organisation_role_versions')
    op.drop_index(op.f('ix_platform_role_template_permissions_template_id'), table_name='platform_role_template_permissions')
    op.drop_table('platform_role_template_permissions')
    op.drop_index(op.f('ix_organisation_roles_organisation_id'), table_name='organisation_roles')
    op.drop_index('ix_org_roles_org_status', table_name='organisation_roles')
    op.drop_table('organisation_roles')
    op.drop_index(op.f('ix_platform_role_templates_code'), table_name='platform_role_templates')
    op.drop_table('platform_role_templates')
    # ### end Alembic commands ###
