"""enforce_strict_tenant_composite_keys

Revision ID: d3e09b9e3c13
Revises: 588a89f2fc81
Create Date: 2026-09-21 10:59:28.839064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e09b9e3c13'
down_revision: Union[str, Sequence[str], None] = '588a89f2fc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_locations', sa.Column('organisation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_client_locations_organisation_id'), 'client_locations', ['organisation_id'], unique=False)
    op.create_unique_constraint('uq_client_location_id_organisation_id', 'client_locations', ['id', 'organisation_id'])
    op.drop_constraint(op.f('fk_client_locations_client_id_clients'), 'client_locations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_locations_organisation_id_organisations'), 'client_locations', 'organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_client_id_organisation_id', 'clients', ['id', 'organisation_id'])
    op.create_foreign_key('fk_client_location_client_org', 'client_locations', 'clients', ['client_id', 'organisation_id'], ['id', 'organisation_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_id_organisation_id', 'clients', type_='unique')
    op.drop_constraint('fk_client_location_client_org', 'client_locations', type_='foreignkey')
    op.drop_constraint(op.f('fk_client_locations_organisation_id_organisations'), 'client_locations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_client_locations_client_id_clients'), 'client_locations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_client_location_id_organisation_id', 'client_locations', type_='unique')
    op.drop_index(op.f('ix_client_locations_organisation_id'), table_name='client_locations')
    op.drop_column('client_locations', 'organisation_id')
    # ### end Alembic commands ###
