filepath = "apps/backend/alembic/versions/10b12c3055fd_prompt_06_commander.py"
with open(filepath, "r") as f:
    content = f.read()

upgrade_add = """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_members', sa.Column('is_commander', sa.Boolean(), nullable=False, server_default='false'))
    
    # Initialize the creator as the commander for existing orgs (safeguard)
    op.execute("UPDATE organisation_members SET is_commander = true WHERE is_creator = true")
    
    op.create_index('uq_org_member_commander', 'organisation_members', ['organisation_id'], unique=True, postgresql_where=sa.text('is_commander = true'))
    
    # Fix schema_version null constraints from previous phase
    op.alter_column('tenant_database_registry', 'schema_version', server_default='0')
    op.alter_column('organisation_database_assignments', 'schema_version', server_default='0')
    op.alter_column('tenant_mongodb_registry', 'schema_version', server_default='0')
"""

content = content.replace("    # ### commands auto generated by Alembic - please adjust! ###\n    op.add_column('organisation_members', sa.Column('is_commander', sa.Boolean(), nullable=False))\n    op.create_index('uq_org_member_commander', 'organisation_members', ['organisation_id'], unique=True, postgresql_where=sa.text('is_commander = true'))", upgrade_add)

downgrade_add = """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_database_registry', 'schema_version', server_default=None)
    op.alter_column('organisation_database_assignments', 'schema_version', server_default=None)
    op.alter_column('tenant_mongodb_registry', 'schema_version', server_default=None)
    
    op.drop_index('uq_org_member_commander', table_name='organisation_members', postgresql_where=sa.text('is_commander = true'))
    op.drop_column('organisation_members', 'is_commander')
"""

content = content.replace("    # ### commands auto generated by Alembic - please adjust! ###\n    op.drop_index('uq_org_member_commander', table_name='organisation_members', postgresql_where=sa.text('is_commander = true'))\n    op.drop_column('organisation_members', 'is_commander')", downgrade_add)

with open(filepath, "w") as f:
    f.write(content)
