from app.modules.customization.models import OrganisationApplication, ApplicationType, ApplicationStatus
import uuid
import pytest
from httpx import ASGITransport, AsyncClient
from jose import jwt
from app.main import app
from app.core.config import settings
from app.db.session import AsyncSessionLocal
from sqlalchemy import text

def make_test_token(user_id: uuid.UUID, email: str) -> str:
    payload = {
        "sub": str(user_id),
        "email": email,
        "aud": "authenticated",
        "exp": 9999999999,
    }
    secret = settings.JWT_SECRET or "test-jwt-secret-for-testing"
    return jwt.encode(payload, secret, algorithm="HS256")

@pytest.mark.asyncio
async def test_application_definition_isolation():
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        # Create Organisation A with User A
        user_a = uuid.uuid4()
        token_a = make_test_token(user_a, "user_a@tenant-a.com")
        tenant_a_name = f"Tenant Alpha {uuid.uuid4().hex[:6]}"
        res_a = await client.post(
            "/api/v1/onboarding",
            json={"name": tenant_a_name, "organisation_type": "Private Limited Company"},
            headers={"Authorization": f"Bearer {token_a}"},
        )
        assert res_a.status_code == 201
        org_a_id = res_a.json()["organisation"]["id"]

        # Create Organisation B with User B
        user_b = uuid.uuid4()
        token_b = make_test_token(user_b, "user_b@tenant-b.com")
        tenant_b_name = f"Tenant Beta {uuid.uuid4().hex[:6]}"
        res_b = await client.post(
            "/api/v1/onboarding",
            json={"name": tenant_b_name, "organisation_type": "Private Limited Company"},
            headers={"Authorization": f"Bearer {token_b}"},
        )
        assert res_b.status_code == 201
        org_b_id = res_b.json()["organisation"]["id"]

        # A should get its own app generated by onboarding hook
        resp_a = await client.get("/api/v1/application", headers={"Authorization": f"Bearer {token_a}"})
        assert resp_a.status_code == 200
        assert resp_a.json()["application_name"] == f"{tenant_a_name} TMS"
        assert resp_a.json()["application_type"] == "STANDARD"
    
        # B should get its own app
        resp_b = await client.get("/api/v1/application", headers={"Authorization": f"Bearer {token_b}"})
        assert resp_b.status_code == 200
        assert resp_b.json()["application_name"] == f"{tenant_b_name} TMS"
        assert resp_b.json()["application_type"] == "STANDARD"
    
        # Update B's app directly in db to test modification
        async with AsyncSessionLocal() as session:
            await session.execute(text(f"""
                UPDATE organisation_applications SET application_type = 'EXTENDED' WHERE organisation_id = '{org_b_id}'
            """))
            await session.commit()
        
        resp_b_2 = await client.get("/api/v1/application", headers={"Authorization": f"Bearer {token_b}"})
        assert resp_b_2.status_code == 200
        assert resp_b_2.json()["application_type"] == "EXTENDED"
    
        # A still sees A's app
        resp_a_2 = await client.get("/api/v1/application", headers={"Authorization": f"Bearer {token_a}"})
        assert resp_a_2.status_code == 200
        assert resp_a_2.json()["application_type"] == "STANDARD"
