"""Add platform control plane tables

Revision ID: 18bebbcc318a
Revises: 22ad882c52f6
Create Date: 2026-09-12 11:43:13.192046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bebbcc318a'
down_revision: Union[str, Sequence[str], None] = '22ad882c52f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_mongodb_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('D1', 'POSTGRESQL', 'MONGODB', 'OTHER', name='providertype'), nullable=False),
    sa.Column('cluster_identifier', sa.String(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'PROVISIONING', 'ASSIGNED', 'MIGRATING', 'SUSPENDED', 'DECOMMISSIONED', 'PROVISIONING_FAILED', name='registrystatus'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_mongodb_registry'))
    )
    op.create_table('organisation_mongodb_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('mongodb_registry_id', sa.UUID(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('namespace_prefix', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mongodb_registry_id'], ['tenant_mongodb_registry.id'], name=op.f('fk_organisation_mongodb_assignments_mongodb_registry_id_tenant_mongodb_registry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_mongodb_assignments_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_mongodb_assignments')),
    sa.UniqueConstraint('organisation_id', name=op.f('uq_organisation_mongodb_assignments_organisation_id'))
    )
    op.create_table('organisation_storage_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('cloudinary_folder_prefix', sa.String(), nullable=False),
    sa.Column('r2_bucket', sa.String(), nullable=False),
    sa.Column('r2_prefix', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_storage_assignments_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_storage_assignments')),
    sa.UniqueConstraint('organisation_id', name=op.f('uq_organisation_storage_assignments_organisation_id'))
    )
    op.create_table('platform_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_platform_audit_logs_organisation_id_organisations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_audit_logs'))
    )
    op.create_table('tenant_database_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('D1', 'POSTGRESQL', 'MONGODB', 'OTHER', name='providertype'), nullable=False),
    sa.Column('database_identifier', sa.String(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'PROVISIONING', 'ASSIGNED', 'MIGRATING', 'SUSPENDED', 'DECOMMISSIONED', 'PROVISIONING_FAILED', name='registrystatus'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('capacity_status', sa.String(), nullable=True),
    sa.Column('assigned_organisation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_organisation_id'], ['organisations.id'], name=op.f('fk_tenant_database_registry_assigned_organisation_id_organisations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_database_registry')),
    sa.UniqueConstraint('database_identifier', name=op.f('uq_tenant_database_registry_database_identifier'))
    )
    op.create_table('organisation_database_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('database_registry_id', sa.UUID(), nullable=False),
    sa.Column('assignment_status', sa.String(), nullable=False),
    sa.Column('provisioning_status', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('last_migration_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['database_registry_id'], ['tenant_database_registry.id'], name=op.f('fk_organisation_database_assignments_database_registry_id_tenant_database_registry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_database_assignments_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_database_assignments')),
    sa.UniqueConstraint('organisation_id', name=op.f('uq_organisation_database_assignments_organisation_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_database_assignments')
    op.drop_table('tenant_database_registry')
    op.drop_table('platform_audit_logs')
    op.drop_table('organisation_storage_assignments')
    op.drop_table('organisation_mongodb_assignments')
    op.drop_table('tenant_mongodb_registry')
    # ### end Alembic commands ###
