"""phase2_identity_and_multitenancy

Revision ID: 8e4205679122
Revises: 
Create Date: 2026-09-10 08:52:37.647232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e4205679122'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('organisation_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='organisation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) between 2 and 160', name=op.f('ck_organisations_org_name_len_check')),
    sa.CheckConstraint('length(trim(organisation_type)) between 2 and 120', name=op.f('ck_organisations_org_type_len_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(full_name)) between 2 and 160', name=op.f('ck_profiles_profile_full_name_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_audit_logs_organisation_id_organisations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organisation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_table('organisation_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', name='member_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_organisation_members_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_organisation_members_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation_members')),
    sa.UniqueConstraint('organisation_id', 'user_id', name='uq_org_member_org_user')
    )
    op.create_index(op.f('ix_organisation_members_organisation_id'), 'organisation_members', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_members_user_id'), 'organisation_members', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    # ### end Alembic commands ###


    # Seed initial roles and permissions
    roles_table = sa.table(
        'roles',
        sa.column('id', sa.UUID),
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('is_system', sa.Boolean),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    permissions_table = sa.table(
        'permissions',
        sa.column('id', sa.UUID),
        sa.column('code', sa.String),
        sa.column('description', sa.String),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    role_perms_table = sa.table(
        'role_permissions',
        sa.column('role_id', sa.UUID),
        sa.column('permission_id', sa.UUID),
    )

    import uuid
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc)
    commander_id = uuid.uuid4()
    admin_id = uuid.uuid4()
    dispatcher_id = uuid.uuid4()
    driver_id = uuid.uuid4()

    op.bulk_insert(
        roles_table,
        [
            {'id': commander_id, 'code': 'COMMANDER', 'name': 'Commander', 'description': 'Primary organisation authority', 'is_system': True, 'created_at': now},
            {'id': admin_id, 'code': 'ADMIN', 'name': 'Admin', 'description': 'Organisation administrator', 'is_system': True, 'created_at': now},
            {'id': dispatcher_id, 'code': 'DISPATCHER', 'name': 'Dispatcher', 'description': 'Duty scheduling and dispatch management', 'is_system': True, 'created_at': now},
            {'id': driver_id, 'code': 'DRIVER', 'name': 'Driver', 'description': 'Trip execution and duty acceptance', 'is_system': True, 'created_at': now},
            {'id': uuid.uuid4(), 'code': 'VIEWER', 'name': 'Viewer', 'description': 'Read-only access to organisation data', 'is_system': True, 'created_at': now},
        ]
    )

    perms_data = [
        ('organisation.manage', 'Manage organisation configuration and settings'),
        ('users.manage', 'Manage organisation members, invites and access'),
        ('roles.manage', 'Manage organisation custom roles and permissions'),
        ('booking.create', 'Create and schedule new booking requests'),
        ('booking.read', 'View customer bookings and history'),
        ('booking.update', 'Modify booking parameters and routing'),
        ('duty.create', 'Create transport duties and schedules'),
        ('duty.assign', 'Assign drivers and fleet vehicles to duties'),
        ('duty.read', 'Inspect scheduled and active duties'),
        ('dispatch.manage', 'Control dispatch board and real-time operations'),
        ('trip.read', 'View active and historical trip records'),
        ('trip.complete', 'Record trip completion, toll, and odometer readings'),
        ('billing.calculate', 'Authoritative billing computation'),
        ('invoice.create', 'Generate invoices and credit notes'),
        ('invoice.read', 'View financial invoices and ledger entries'),
        ('payment.collect', 'Accept and record customer payments'),
        ('expense.create', 'Submit fuel, toll, and driver operational expenses'),
        ('reports.read', 'Access analytical reports and P&L statements'),
    ]

    inserted_perms = []
    for code, desc in perms_data:
        p_id = uuid.uuid4()
        inserted_perms.append({'id': p_id, 'code': code, 'description': desc, 'created_at': now})

    op.bulk_insert(permissions_table, inserted_perms)

    # Link all permissions to COMMANDER
    commander_perms = [{'role_id': commander_id, 'permission_id': p['id']} for p in inserted_perms]
    op.bulk_insert(role_perms_table, commander_perms)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_organisation_members_user_id'), table_name='organisation_members')
    op.drop_index(op.f('ix_organisation_members_organisation_id'), table_name='organisation_members')
    op.drop_table('organisation_members')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('organisations')
    op.execute('DROP TYPE IF EXISTS organisation_status CASCADE;')
    op.execute('DROP TYPE IF EXISTS member_status CASCADE;')
    # ### end Alembic commands ###
