"""phase3_master_data

Revision ID: f00940ddeebc
Revises: 8e4205679122
Create Date: 2026-09-10 09:03:58.522882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f00940ddeebc'
down_revision: Union[str, Sequence[str], None] = '8e4205679122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='customer_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) between 2 and 160', name=op.f('ck_customers_ck_customer_name_len')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_customers_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_organisation_id'), 'customers', ['organisation_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('vendor_type', sa.Enum('FLEET_SUPPLIER', 'WORKSHOP', 'FUEL_PARTNER', 'BROKER', 'OTHER', name='vendor_type'), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('bank_account_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account_number', sa.String(length=64), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='vendor_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(name)) between 2 and 160', name=op.f('ck_vendors_ck_vendor_name_len')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_vendors_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_organisation_id'), 'vendors', ['organisation_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('alternate_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('license_number', sa.String(length=64), nullable=False),
    sa.Column('license_type', sa.String(length=64), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('badge_number', sa.String(length=64), nullable=True),
    sa.Column('aadhaar_last4', sa.String(length=4), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('driver_type', sa.Enum('PERMANENT', 'CONTRACT', 'MARKET', name='driver_employment_type'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_DUTY', 'ON_LEAVE', 'INACTIVE', name='driver_operational_status'), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(full_name)) between 2 and 160', name=op.f('ck_drivers_ck_driver_name_len')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_drivers_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_drivers_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivers')),
    sa.UniqueConstraint('organisation_id', 'license_number', name='uq_driver_org_license'),
    sa.UniqueConstraint('organisation_id', 'phone', name='uq_driver_org_phone')
    )
    op.create_index(op.f('ix_drivers_organisation_id'), 'drivers', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_drivers_vendor_id'), 'drivers', ['vendor_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('registration_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.Enum('TRUCK', 'TRAILER', 'CONTAINER', 'TANKER', 'TIPPER', 'TEMPO', 'PICKUP', 'OTHER', name='vehicle_body_type'), nullable=False),
    sa.Column('ownership_type', sa.Enum('OWNED', 'LEASED', 'ATTACHED', name='vehicle_ownership_type'), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'CNG', 'ELECTRIC', 'PETROL', name='fuel_type'), nullable=False),
    sa.Column('payload_capacity_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume_cft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fastag_id', sa.String(length=64), nullable=True),
    sa.Column('gps_device_id', sa.String(length=64), nullable=True),
    sa.Column('rc_number', sa.String(length=64), nullable=True),
    sa.Column('rc_expiry', sa.Date(), nullable=True),
    sa.Column('fitness_expiry', sa.Date(), nullable=True),
    sa.Column('permit_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('puc_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_DUTY', 'MAINTENANCE', 'DECOMMISSIONED', name='vehicle_operational_status'), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(registration_number)) between 4 and 32', name=op.f('ck_vehicles_ck_vehicle_reg_len')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_vehicles_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vehicles_vendor_id_vendors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('organisation_id', 'registration_number', name='uq_vehicle_org_reg')
    )
    op.create_index(op.f('ix_vehicles_organisation_id'), 'vehicles', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vendor_id'), 'vehicles', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vendor_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_organisation_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_vendor_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_organisation_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_vendors_organisation_id'), table_name='vendors')
    op.drop_index(op.f('ix_customers_organisation_id'), table_name='customers')
    op.drop_table('customers')
    op.execute('DROP TYPE IF EXISTS customer_status CASCADE;')
    op.execute('DROP TYPE IF EXISTS vendor_type CASCADE;')
    op.execute('DROP TYPE IF EXISTS vendor_status CASCADE;')
    op.execute('DROP TYPE IF EXISTS driver_employment_type CASCADE;')
    op.execute('DROP TYPE IF EXISTS driver_operational_status CASCADE;')
    op.execute('DROP TYPE IF EXISTS vehicle_body_type CASCADE;')
    op.execute('DROP TYPE IF EXISTS vehicle_ownership_type CASCADE;')
    op.execute('DROP TYPE IF EXISTS fuel_type CASCADE;')
    op.execute('DROP TYPE IF EXISTS vehicle_operational_status CASCADE;')
    # ### end Alembic commands ###
