"""compliance_engine_phase_5_5

Revision ID: 1f4636f4238e
Revises: b31289c6bda8
Create Date: 2026-09-12 04:21:53.941124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f4636f4238e'
down_revision: Union[str, Sequence[str], None] = 'b31289c6bda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('category', sa.Enum('STATUTORY', 'CONTRACTUAL', 'INTERNAL', 'SAFETY', name='compliance_category'), nullable=False),
    sa.Column('entity_type', sa.Enum('ORGANISATION', 'VEHICLE', 'DRIVER', 'VENDOR', 'CUSTOMER', 'SERVICE', 'ROUTE', 'DUTY', name='compliance_entity_type'), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('validity_period_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('source_reference', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_compliance_requirements_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_requirements')),
    sa.UniqueConstraint('organisation_id', 'code', name='uq_comp_req_org_code')
    )
    op.create_index(op.f('ix_compliance_requirements_organisation_id'), 'compliance_requirements', ['organisation_id'], unique=False)
    op.create_table('compliance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('ORGANISATION', 'VEHICLE', 'DRIVER', 'VENDOR', 'CUSTOMER', 'SERVICE', 'ROUTE', 'DUTY', name='compliance_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('MISSING', 'PENDING', 'VERIFICATION_REQUIRED', 'VALID', 'EXPIRING_SOON', 'EXPIRED', 'REJECTED', 'WAIVED', name='compliance_status'), nullable=False),
    sa.Column('document_number', sa.String(length=64), nullable=True),
    sa.Column('document_url', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=256), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verification_method', sa.String(length=128), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_compliance_records_organisation_id_organisations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], name=op.f('fk_compliance_records_requirement_id_compliance_requirements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['profiles.id'], name=op.f('fk_compliance_records_verified_by_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_records')),
    sa.UniqueConstraint('organisation_id', 'requirement_id', 'entity_type', 'entity_id', name='uq_comp_record_entity_req')
    )
    op.create_index(op.f('ix_compliance_records_entity_id'), 'compliance_records', ['entity_id'], unique=False)
    op.create_index(op.f('ix_compliance_records_expiry_date'), 'compliance_records', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_compliance_records_organisation_id'), 'compliance_records', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_compliance_records_requirement_id'), 'compliance_records', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_compliance_records_status'), 'compliance_records', ['status'], unique=False)
    op.create_table('compliance_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('compliance_record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('VERIFY', 'REJECT', 'WAIVE', name='compliance_verification_action'), nullable=False),
    sa.Column('previous_status', sa.Enum('MISSING', 'PENDING', 'VERIFICATION_REQUIRED', 'VALID', 'EXPIRING_SOON', 'EXPIRED', 'REJECTED', 'WAIVED', name='compliance_status'), nullable=False),
    sa.Column('new_status', sa.Enum('MISSING', 'PENDING', 'VERIFICATION_REQUIRED', 'VALID', 'EXPIRING_SOON', 'EXPIRED', 'REJECTED', 'WAIVED', name='compliance_status'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('comments', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['profiles.id'], name=op.f('fk_compliance_verifications_actor_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['compliance_record_id'], ['compliance_records.id'], name=op.f('fk_compliance_verifications_compliance_record_id_compliance_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_compliance_verifications_organisation_id_organisations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_verifications'))
    )
    op.create_index(op.f('ix_compliance_verifications_compliance_record_id'), 'compliance_verifications', ['compliance_record_id'], unique=False)
    op.create_index(op.f('ix_compliance_verifications_organisation_id'), 'compliance_verifications', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_verifications_organisation_id'), table_name='compliance_verifications')
    op.drop_index(op.f('ix_compliance_verifications_compliance_record_id'), table_name='compliance_verifications')
    op.drop_table('compliance_verifications')
    op.drop_index(op.f('ix_compliance_records_status'), table_name='compliance_records')
    op.drop_index(op.f('ix_compliance_records_requirement_id'), table_name='compliance_records')
    op.drop_index(op.f('ix_compliance_records_organisation_id'), table_name='compliance_records')
    op.drop_index(op.f('ix_compliance_records_expiry_date'), table_name='compliance_records')
    op.drop_index(op.f('ix_compliance_records_entity_id'), table_name='compliance_records')
    op.drop_table('compliance_records')
    op.drop_index(op.f('ix_compliance_requirements_organisation_id'), table_name='compliance_requirements')
    op.drop_table('compliance_requirements')
    # ### end Alembic commands ###
