"""phase5_financial_engine

Revision ID: b31289c6bda8
Revises: 0e881b3debad
Create Date: 2026-09-10 11:06:27.705197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b31289c6bda8'
down_revision: Union[str, Sequence[str], None] = '0e881b3debad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    op.create_index(op.f('ix_payment_events_provider_event_id'), 'payment_events', ['provider_event_id'], unique=True)
    op.create_table('financial_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_financial_audit_logs_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_audit_logs'))
    )
    op.create_index(op.f('ix_financial_audit_logs_organisation_id'), 'financial_audit_logs', ['organisation_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FINALIZED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'VOID', name='invoice_status'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_invoices_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_organisation_id'), 'invoices', ['organisation_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unallocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'REVERSED', name='payment_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_payments_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_payments_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_organisation_id'), 'payments', ['organisation_id'], unique=False)
    op.create_table('invoice_tax_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('tax_name', sa.String(length=64), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_tax_lines_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_tax_lines'))
    )
    op.create_index(op.f('ix_invoice_tax_lines_invoice_id'), 'invoice_tax_lines', ['invoice_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payment_allocations_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_allocations_payment_id_payments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    op.create_index(op.f('ix_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_table('rate_card_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_card_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('FIXED_TRIP', 'PER_KM', 'PER_HOUR', 'MINIMUM_CHARGE', 'EXTRA_KM', 'EXTRA_HOUR', 'WAITING_CHARGE', 'NIGHT_SURCHARGE', 'AIRPORT_SURCHARGE', 'TOLL', 'PARKING', 'DRIVER_ALLOWANCE', 'ADDITIONAL_STOP', 'CANCELLATION_FEE', 'PERCENTAGE_SURCHARGE', 'PERCENTAGE_DISCOUNT', 'TAX_CGST', 'TAX_SGST', 'TAX_IGST', 'CUSTOM_ADJUSTMENT', name='rate_rule_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_included', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.Column('percentage_value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], name=op.f('fk_rate_card_rules_rate_card_version_id_rate_card_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_card_rules'))
    )
    op.create_index(op.f('ix_rate_card_rules_rate_card_version_id'), 'rate_card_rules', ['rate_card_version_id'], unique=False)
    op.create_table('payables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=False),
    sa.Column('duty_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advances', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SETTLED', 'CANCELLED', name='payable_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_payables_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], name=op.f('fk_payables_duty_id_duties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_payables_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_payables_vendor_id_vendors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payables'))
    )
    op.create_index(op.f('ix_payables_driver_id'), 'payables', ['driver_id'], unique=False)
    op.create_index(op.f('ix_payables_organisation_id'), 'payables', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_payables_reference_number'), 'payables', ['reference_number'], unique=False)
    op.create_index(op.f('ix_payables_vendor_id'), 'payables', ['vendor_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('duty_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('FUEL', 'TOLL', 'PARKING', 'MAINTENANCE', 'DRIVER_ALLOWANCE', 'FOOD', 'MISCELLANEOUS', name='expense_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attachment_url', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_expenses_driver_id_drivers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], name=op.f('fk_expenses_duty_id_duties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_expenses_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_expenses_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_expenses_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_driver_id'), 'expenses', ['driver_id'], unique=False)
    op.create_index(op.f('ix_expenses_duty_id'), 'expenses', ['duty_id'], unique=False)
    op.create_index(op.f('ix_expenses_organisation_id'), 'expenses', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_expenses_trip_id'), 'expenses', ['trip_id'], unique=False)
    op.create_index(op.f('ix_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False)
    op.create_table('financial_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('duty_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('rate_card_version_id', sa.UUID(), nullable=True),
    sa.Column('operational_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('surcharge_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_financial_snapshots_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], name=op.f('fk_financial_snapshots_duty_id_duties'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_financial_snapshots_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], name=op.f('fk_financial_snapshots_rate_card_version_id_rate_card_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_financial_snapshots_trip_id_trips'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_snapshots'))
    )
    op.create_index(op.f('ix_financial_snapshots_duty_id'), 'financial_snapshots', ['duty_id'], unique=False)
    op.create_index(op.f('ix_financial_snapshots_organisation_id'), 'financial_snapshots', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_financial_snapshots_trip_id'), 'financial_snapshots', ['trip_id'], unique=False)
    op.create_table('payable_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payable_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_deduction', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payable_id'], ['payables.id'], name=op.f('fk_payable_lines_payable_id_payables'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payable_lines'))
    )
    op.create_index(op.f('ix_payable_lines_payable_id'), 'payable_lines', ['payable_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payable_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settlement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payable_id'], ['payables.id'], name=op.f('fk_settlements_payable_id_payables'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements'))
    )
    op.create_index(op.f('ix_settlements_payable_id'), 'settlements', ['payable_id'], unique=False)
    op.create_table('billing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('duty_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ELIGIBLE', 'PENDING', 'INVOICED', 'CANCELLED', name='billing_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_billing_records_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], name=op.f('fk_billing_records_duty_id_duties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_billing_records_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['financial_snapshots.id'], name=op.f('fk_billing_records_snapshot_id_financial_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_records')),
    sa.UniqueConstraint('duty_id', name='uq_billing_duty')
    )
    op.create_index(op.f('ix_billing_records_customer_id'), 'billing_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_billing_records_duty_id'), 'billing_records', ['duty_id'], unique=False)
    op.create_index(op.f('ix_billing_records_invoice_id'), 'billing_records', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_records_organisation_id'), 'billing_records', ['organisation_id'], unique=False)
    op.create_table('financial_snapshot_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_tax', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rate_card_rules.id'], name=op.f('fk_financial_snapshot_lines_rule_id_rate_card_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['financial_snapshots.id'], name=op.f('fk_financial_snapshot_lines_snapshot_id_financial_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_snapshot_lines'))
    )
    op.create_index(op.f('ix_financial_snapshot_lines_snapshot_id'), 'financial_snapshot_lines', ['snapshot_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('billing_record_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['billing_record_id'], ['billing_records.id'], name=op.f('fk_invoice_lines_billing_record_id_billing_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.drop_column('rate_card_versions', 'extra_hour_rate')
    op.drop_column('rate_card_versions', 'base_hours')
    op.drop_column('rate_card_versions', 'driver_allowance')
    op.drop_column('rate_card_versions', 'night_allowance')
    op.drop_column('rate_card_versions', 'base_km')
    op.drop_column('rate_card_versions', 'base_fare')
    op.drop_column('rate_card_versions', 'extra_km_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_card_versions', sa.Column('extra_km_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rate_card_versions', sa.Column('base_fare', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rate_card_versions', sa.Column('base_km', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rate_card_versions', sa.Column('night_allowance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rate_card_versions', sa.Column('driver_allowance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rate_card_versions', sa.Column('base_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('rate_card_versions', sa.Column('extra_hour_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_financial_snapshot_lines_snapshot_id'), table_name='financial_snapshot_lines')
    op.drop_table('financial_snapshot_lines')
    op.drop_index(op.f('ix_billing_records_organisation_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_invoice_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_duty_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_customer_id'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index(op.f('ix_settlements_payable_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_payable_lines_payable_id'), table_name='payable_lines')
    op.drop_table('payable_lines')
    op.drop_index(op.f('ix_financial_snapshots_trip_id'), table_name='financial_snapshots')
    op.drop_index(op.f('ix_financial_snapshots_organisation_id'), table_name='financial_snapshots')
    op.drop_index(op.f('ix_financial_snapshots_duty_id'), table_name='financial_snapshots')
    op.drop_table('financial_snapshots')
    op.drop_index(op.f('ix_expenses_vehicle_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_trip_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_organisation_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_duty_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_driver_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_payables_vendor_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_reference_number'), table_name='payables')
    op.drop_index(op.f('ix_payables_organisation_id'), table_name='payables')
    op.drop_index(op.f('ix_payables_driver_id'), table_name='payables')
    op.drop_table('payables')
    op.drop_index(op.f('ix_rate_card_rules_rate_card_version_id'), table_name='rate_card_rules')
    op.drop_table('rate_card_rules')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_invoice_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_invoice_tax_lines_invoice_id'), table_name='invoice_tax_lines')
    op.drop_table('invoice_tax_lines')
    op.drop_index(op.f('ix_payments_organisation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_organisation_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_financial_audit_logs_organisation_id'), table_name='financial_audit_logs')
    op.drop_table('financial_audit_logs')
    op.drop_index(op.f('ix_payment_events_provider_event_id'), table_name='payment_events')
    op.drop_table('payment_events')
    # ### end Alembic commands ###

    # Drop custom enums
    op.execute("DROP TYPE IF EXISTS rate_rule_type CASCADE;")
    op.execute("DROP TYPE IF EXISTS billing_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS invoice_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS payment_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS payable_status CASCADE;")
    op.execute("DROP TYPE IF EXISTS expense_category CASCADE;")
